const express=require('express')
const app=express()
app.use(express.json())
const cors=require('cors')
app.use(cors())
const path=require("path")
const connection=require('./mongodb.js')
connection()
const route=require('./routes/user.js')
const route1=require('./routes/payment.js')
app.use('/userzerco',route)
app.use('/paymentzerco',route1)
app.listen(3000,()=>{
    console.log("port connected")
})